[[zrl]]
arch = "aarch64"
git-tree-sha1 = "df93f97c9e7bd1b834c70b096c6dd84945e70559"
libc = "glibc"
os = "linux"

    [[zrl.download]]
    sha256 = "89c6cdd66ef746ebfb4c57a56dfa57e0029bb5b07687942a1fa53aefdb909f6b"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.aarch64-linux-gnu.tar.gz"
[[zrl]]
arch = "aarch64"
git-tree-sha1 = "2b24a22b0f8efcb66d0a2f846839f6ddc23baee9"
libc = "musl"
os = "linux"

    [[zrl.download]]
    sha256 = "286aad6dec9ab02a788fc56aec36c157c8d5d51eebb5e378c50189f70ad3b15a"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.aarch64-linux-musl.tar.gz"
[[zrl]]
arch = "armv7l"
git-tree-sha1 = "e0793e318a4680246e3c22eda7020eb67140aa13"
libc = "glibc"
os = "linux"

    [[zrl.download]]
    sha256 = "22e57605b9add467c76dcd71f500fdc64b3292df99011858dfea4f2c068c9a4e"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.armv7l-linux-gnueabihf.tar.gz"
[[zrl]]
arch = "armv7l"
git-tree-sha1 = "ce667e2615554990b0f69ccd1b91f43452d9a8b2"
libc = "musl"
os = "linux"

    [[zrl.download]]
    sha256 = "dfcf70fc694c088607ad709ac4dd6227ff60ee6ea330adbd95f12e67f9fe82ac"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.armv7l-linux-musleabihf.tar.gz"
[[zrl]]
arch = "i686"
git-tree-sha1 = "e0136d91ed03d9bd2e09092af759cac5824f5a0f"
libc = "glibc"
os = "linux"

    [[zrl.download]]
    sha256 = "9aa8659ccff387258e11e6582470c093b689df903cdd9459199c43d8094c9b9b"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.i686-linux-gnu.tar.gz"
[[zrl]]
arch = "i686"
git-tree-sha1 = "4950e705b016862c238b372f96c01152d49650d0"
libc = "musl"
os = "linux"

    [[zrl.download]]
    sha256 = "866a94a6a3fa8f3e297b5268f737035d914198bc9a62e4fcaa49742e22226833"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.i686-linux-musl.tar.gz"
[[zrl]]
arch = "i686"
git-tree-sha1 = "78d2d297b72006f9b4226f9c131581e2759ef2d5"
os = "windows"

    [[zrl.download]]
    sha256 = "f26e1dca9ceb352b15e20bf9fb89f85a85b68d56c4051755cdb3b7820ddd7138"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.i686-w64-mingw32.tar.gz"
[[zrl]]
arch = "powerpc64le"
git-tree-sha1 = "9faf2db5ab1c393593fce8b02f285abd96610183"
libc = "glibc"
os = "linux"

    [[zrl.download]]
    sha256 = "d8c0ca5a766bbb33898d1f4f5f4960cf18d3d982caa64c54c86c675236994bfd"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.powerpc64le-linux-gnu.tar.gz"
[[zrl]]
arch = "x86_64"
git-tree-sha1 = "6233a45298e1a623016044e31d8ee4b1f1403d83"
os = "macos"

    [[zrl.download]]
    sha256 = "354d7bfc7c43668db2aa48bcf64fbbe0918e86da57b8b27d7b7a392300b47d00"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.x86_64-apple-darwin14.tar.gz"
[[zrl]]
arch = "x86_64"
git-tree-sha1 = "47786901f044f055d5a6e0f2122991e0ffde1015"
libc = "glibc"
os = "linux"

    [[zrl.download]]
    sha256 = "828ad8e2b1b8577cb84f20d1668a46ed84d42f125df43585b3453547c5e535ef"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.x86_64-linux-gnu.tar.gz"
[[zrl]]
arch = "x86_64"
git-tree-sha1 = "a704b6fbf44e46cd3b58bf3821d5d45f2410cdab"
libc = "musl"
os = "linux"

    [[zrl.download]]
    sha256 = "ff068057f27c4962b5f6e217115eb82bd3e595447f264cbf32bc2b2068726a00"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.x86_64-linux-musl.tar.gz"
[[zrl]]
arch = "x86_64"
git-tree-sha1 = "0abaca55117a5346b4d9cf3e81929d7bc950828b"
os = "freebsd"

    [[zrl.download]]
    sha256 = "22abda738b174607efc9bbebefbe02877adb5cf7d551e22cf49d5c258858c0e9"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.x86_64-unknown-freebsd11.1.tar.gz"
[[zrl]]
arch = "x86_64"
git-tree-sha1 = "1d74edbc9ba16de19f6fbe890a98571302dcea18"
os = "windows"

    [[zrl.download]]
    sha256 = "8668cd147e3d0653ad57cdaa5020d49f9a17884777a20523407c441fd9e0b0f9"
    url = "https://github.com/JuliaBinaryWrappers/zrl_jll.jl/releases/download/zrl-v1.1.1+0/zrl.v1.1.1.x86_64-w64-mingw32.tar.gz"
